### ISSUE TITLE
Dat Wikis?

### ISSUE THREAD

**Issue by LWFlouisa** [beakerbrowser/explore#8]
Is there currently a way to integrate the wikia format with P2P Dat sites? By this, I mean without having to wrap it in an iframe like I do for my Yacy instance.

**Comment by pfrazee** [comment]
Not quite yet, but we're working on some updates that'll make that possible. One is called "Multiwriter" which will make it possible for multiple people to edit a dat. Another is called "Ephemeral messaging" which will make it possible for users to message each other, so that they could propose changes.
